const ROOT_HEADER = document.getElementById('header')
const ROOT_PRODUCTS = document.getElementById('products')
const ROOT_SHOP = document.getElementById('shop')
const ROOT_LOAD = document.getElementById('preloader')
const ROOT_ERROR = document.getElementById('error')